pipeline {

    agent any

    stages {

        stage('Clone Repository') {
            steps {
                git 'https://github.com/SUBASH-2005/ChronicKidneyDiseasePrediction.git'
            }
        }

        stage('Install Dependencies') {
            steps {
                bat 'pip install -r requirements.txt'
            }
        }

        stage('Train Model') {
            steps {
                bat 'python src/train.py'
            }
        }

        stage('Build Docker Image') {
            steps {
                bat 'docker build -t ckd-app .'
            }
        }

        stage('Run Container') {
            steps {
                bat 'docker run -d -p 8501:8501 ckd-app'
            }
        }

    }
}